const BUILT_IN = [
  {word:'because',sentence:'I wore my coat because it was cold.',pattern:'because'},
  {word:'beautiful',sentence:'The peacock has beautiful feathers.',pattern:'-ful ending'},
  {word:'different',sentence:'The two shells look different.',pattern:'double consonants'},
  {word:'important',sentence:'It is important to listen carefully.',pattern:'-ant ending'},
  {word:'thought',sentence:'I thought about the answer.',pattern:'-ough sound'},
  {word:'enough',sentence:'There is enough cake for everyone.',pattern:'-ough sound'},
  {word:'favourite',sentence:'Blue is my favourite colour.',pattern:'our spelling'},
  {word:'remember',sentence:'Remember to bring your reading book.',pattern:'prefix re-'},
  {word:'straight',sentence:'Draw a straight line with your ruler.',pattern:'-aigh sound'},
  {word:'surprise',sentence:'The party was a lovely surprise.',pattern:'-prise ending'}
];
const WORD_HELP = {
  because:{sounds:['b','e','c','au','se'],syllables:['be','cause'],parts:['be','cause'],tricky:'au',tip:'Think: big elephants can always understand small elephants.'},
  beautiful:{sounds:['beau','ti','ful'],syllables:['beau','ti','ful'],parts:['beau','ti','ful'],tricky:'eau',build:['b','be','bea','beau'],teaching:'Beautiful. Beau, ti, ful. The first part is spelled B, E, A, U. Beau. Then T, I. Then F, U, L.',tip:'The unusual beginning is beau. Build it one letter at a time: b, be, bea, beau. Then add ti and ful.'},
  different:{sounds:['dif','fer','ent'],syllables:['dif','fer','ent'],parts:['differ','ent'],tricky:'ff',tip:'It begins with differ, as in two things differ.'},
  important:{sounds:['im','por','tant'],syllables:['im','por','tant'],parts:['import','ant'],tricky:'ant',tip:'The ending is ant, like the small insect.'},
  thought:{sounds:['th','ough','t'],syllables:['thought'],parts:['th','ought'],tricky:'ough',tip:'The four letters ough work together in this word.'},
  enough:{sounds:['e','n','ough'],syllables:['e','nough'],parts:['en','ough'],tricky:'ough',tip:'Enough ends with ough, even though it sounds like “uff”.'},
  favourite:{sounds:['fav','our','ite'],syllables:['fav','our','ite'],parts:['favour','ite'],tricky:'our',tip:'In British English, favourite keeps the u in favour.'},
  remember:{sounds:['re','mem','ber'],syllables:['re','mem','ber'],parts:['re','member'],tricky:'mem',tip:'Re + member: remember to keep the whole word member.'},
  straight:{sounds:['str','aigh','t'],syllables:['straight'],parts:['str','aight'],tricky:'aigh',tip:'Straight has the word eight at the end with “stra” in front.'},
  surprise:{sounds:['sur','prise'],syllables:['sur','prise'],parts:['sur','prise'],tricky:'rpr',tip:'There is an r before and after the first p: sur-pri-se.'}
};
const WORLDS=[
  ['🌿','Sound Trail',['Sound detectives','Vowel teams','Long and short sounds','Consonant teams','Sound Trail review']],
  ['💧','Suffix Springs',['Adding -ful and -less','Adding -ly','Adding -ment and -ness','Changing root words','Suffix Springs review']],
  ['⛰️','Prefix Peaks',['re- and dis-','mis- and in-','sub- and inter-','Word families','Prefix Peaks review']],
  ['⚓','Homophone Harbour',['Here or hear?','There, their and they’re','To, too and two','Meaning chooses spelling','Homophone Harbour review']],
  ['🏰','Tricky Word Tower',['Unexpected vowels','Silent letters','The many sounds of -ough','Commonly confused words','Tricky Word review']],
  ['🌟','Mastery Mountain',['Roots and relatives','Syllable strategies','Words in sentences','Cumulative recall','Wordwood champion']]
];
const WORD_BANK = `accident actual address answer appear arrive believe bicycle breath breathe build busy business calendar caught centre century certain circle complete consider continue decide describe disappear early earth eight eighth exercise experience experiment extreme famous February forward fruit grammar group guard guide heard heart height history imagine increase interest island knowledge learn length library material medicine mention minute natural naughty notice occasion occasionally often opposite ordinary particular peculiar perhaps popular position possess possession possible potatoes pressure probably promise purpose quarter question recent regular reign sentence separate special strange strength suppose therefore though although through various weight woman women`.toLowerCase().split(' ');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let state={queue:[],index:0,records:{},coins:0,xp:0,boss:[],bossIndex:0,bossCorrect:0,locked:false,questType:'main',questNumber:1,activeWords:[]};
const legacySave=JSON.parse(localStorage.getItem('spellQuest')||'{}');
const profileBook=JSON.parse(localStorage.getItem('spellQuestProfiles')||'{"active":"explorer","profiles":[{"id":"explorer","name":"Explorer"}]}');
let saved=JSON.parse(localStorage.getItem(`spellQuest:${profileBook.active}`)||JSON.stringify(legacySave));
if(!saved.weeklyWords){const legacy=((saved.weeklyPlan||{})[Number(saved.activeWeek)||1]||[]).filter(Boolean);if(legacy.length)saved.weeklyWords=legacy}
$('#coinCount').textContent=saved.totalCoins||0; $('#starCount').textContent=saved.totalStars||0;$('#activeChildPill').textContent=`🧒 ${activeProfile().name}`;
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id+'Screen').classList.add('active');scrollTo(0,0);if(id==='home')renderHome();if(id==='parent')renderParent();if(id==='map')renderMap()}
$$('[data-nav]').forEach(b=>b.onclick=()=>show(b.dataset.nav));
$('#mapBtn').onclick=()=>show('map');
function nextQuest(){const complete=saved.completedQuests||[];return Math.min(30,QUESTS.find(q=>!complete.includes(q.id))?.id||30)}
function renderHome(){const q=QUESTS[nextQuest()-1];$('#homeQuestLabel').textContent=`WORLD ${q.world} · QUEST ${q.id} OF 30${q.test?' · PATH TEST':''}`;$('#startBtn').innerHTML=`Begin Quest ${q.id} <span>→</span>`;renderWeeklyEntrances()}
function renderMap(){const complete=saved.completedQuests||[],ready=nextQuest();let n=0;$('#questWorlds').innerHTML=`<div class="forest-decor" aria-hidden="true"><span>🦉</span><span>🐿️</span><span>🦋</span><span>🦊</span></div><div class="trail-start">🏕️ START HERE</div>`+WORLDS.map(([icon,name,quests],world)=>`<section class="world-row world-${world+1}"><div class="world-title"><span>${icon}</span><div><h3>${name}</h3><small>Quests ${n+1}–${n+5}</small></div></div><div class="quest-track">${quests.map(()=>{n++;const q=QUESTS[n-1],status=complete.includes(n)?'complete':n===ready?'ready':'locked',playable=status!=='locked';return `<button class="quest-node ${status} ${q.test?'path-test':''}" data-quest="${n}" ${playable?'':'disabled'}><b>${q.test?'🏆':status==='complete'?'✓':status==='locked'?'🔒':'●'} ${n}</b><span>${q.title}</span><small>${q.test?'PATH TEST':status==='complete'?'REPLAY':'PLAY'}</small>${n===ready?'<i class="player-marker">🐲<em>You are here</em></i>':''}</button>`}).join('')}</div><div class="world-landmark" aria-hidden="true">${['🍄🌲','🌊🪷','⛰️🌲','⛵⚓','🏰🌙','⭐🏆'][world]}</div></section>`).join('')+`<div class="trail-finish">🏆 WORDWOOD CHAMPION</div>`;$$('.quest-node:not(.locked)').forEach(b=>b.onclick=()=>start('main',Number(b.dataset.quest)));renderWeeklyEntrances()}
function weeklyWords(){return (saved.weeklyWords||[]).filter(Boolean)}
function wordData(words){return words.map(word=>({word,sentence:`Can you spell ${word}?`,pattern:guessPattern(word)}))}
function getWords(type=state.questType,questNumber=state.questNumber){if(type==='weekly')return wordData(weeklyWords()).slice(0,20);if(type==='focus')return wordData(saved.focusWords||[]).slice(0,10);return questWordData(QUESTS[questNumber-1])}
function renderWeeklyEntrances(){const words=weeklyWords(),ready=words.length>=3,preview=words.slice(0,6).join(' · ')+(words.length>6?'…':'');if($('#weeklyHomeCard')){$('#weeklyHomeCard').hidden=!ready;$('#weeklyHomeTitle').textContent=`${words.length} school word${words.length===1?'':'s'} are ready!`;$('#weeklyHomeWords').textContent=preview}if($('#weeklyMapCard')){$('#weeklyMapCard').hidden=!ready;$('#weeklyMapWords').textContent=preview}}
function guessPattern(w){if(/ough/.test(w))return '-ough sound';if(/tion/.test(w))return '-tion ending';if(/ful$/.test(w))return '-ful ending';if(/ly$/.test(w))return '-ly ending';if(/([a-z])\1/.test(w))return 'double consonants';return 'whole word'}
function start(type='main',questNumber=nextQuest()){const pool=getWords(type,questNumber);if((type==='weekly'||type==='focus')&&pool.length<3){show('parent');if(type==='weekly')$('#saveStatus').textContent='Add at least 3 words to unlock the sidequest.';return}let words=pool.slice(0,10);if(type==='weekly'&&pool.length>10){const offset=(Number(saved.weeklyOffset)||0)%pool.length;words=Array.from({length:10},(_,i)=>pool[(offset+i)%pool.length]);saved.weeklyOffset=(offset+10)%pool.length;persist()}const isTest=type==='main'&&QUESTS[questNumber-1].test;state={queue:words.map((data,i)=>({data,mode:isTest?0:i%3,repeat:false})),index:0,records:{},coins:0,xp:0,boss:[],bossIndex:0,bossCorrect:0,locked:false,questType:type,questNumber,activeWords:words};words.forEach(x=>state.records[x.word]={attempts:0,firstCorrect:null,correct:false});show('game');renderQuestion()}
$('#startBtn').onclick=()=>start('main',nextQuest());$('#weeklyHomeStart').onclick=()=>start('weekly');$('#weeklyMapStart').onclick=()=>start('weekly');$('#parentSidequestStart').onclick=()=>start('weekly');$('#startFocusQuest').onclick=()=>start('focus');$('#playAgain').onclick=()=>start(state.questType,state.questNumber);$('#exitBtn').onclick=()=>show(state.questType==='main'?'map':'home');renderHome();
function availableVoices(){return 'speechSynthesis'in window?speechSynthesis.getVoices().filter(v=>/^en([-_]|$)/i.test(v.lang)):[]}
function bestVoice(){const voices=availableVoices(),chosen=saved.voiceName&&voices.find(v=>v.name===saved.voiceName);if(chosen)return chosen;const preferred=['Sonia','Libby','Ryan','Google UK English Female','Google UK English Male','Serena','Daniel','Kate','British English','Microsoft Zira'];return voices.sort((a,b)=>{const score=v=>{const name=v.name.toLowerCase();let n=/en-gb/i.test(v.lang)?30:0;n+=v.localService?5:0;preferred.forEach((p,i)=>{if(name.includes(p.toLowerCase()))n+=100-i});if(/compact|espeak|festival/i.test(name))n-=30;return n};return score(b)-score(a)})[0]}
function speak(word,sentence=''){if(!('speechSynthesis'in window)){setFeedback('Your browser cannot speak, but you can still play.',false);return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(sentence||word),voice=bestVoice();u.lang=voice?.lang||'en-GB';if(voice)u.voice=voice;u.rate=.88;u.pitch=1.04;u.volume=1;speechSynthesis.speak(u)}
function current(){return state.queue[state.index]}
function renderQuestion(){state.locked=false;const q=current();if(!q){startBoss();return}const {word,sentence}=q.data,total=Object.keys(state.records).length,step=Math.min(state.index+1,total);$('#roundLabel').textContent=state.questType==='weekly'?`Sidequest · Word ${step} of ${total}`:`Quest ${state.questNumber} · Word ${step} of ${total}`;$('#xpLabel').textContent=`${state.xp} XP`;$('#progressBar').style.width=`${Math.min(100,(state.index/state.queue.length)*100)}%`;$('#feedback').textContent='';$('#feedback').className='feedback';$('#owlText').textContent=q.repeat?'This one is back for another try — you’ve got this!':'I’m with you! Have a go.';
  if(q.mode===0){$('#modeBadge').textContent='🔊 Hear & Spell';$('#promptArea').innerHTML=`<h2>Listen to the word</h2><p class="instruction">Tap the sound button, then type the spelling word you hear in the sentence.</p><button class="speak-btn" aria-label="Hear the example sentence">🔊</button><p class="sentence">The example sentence says the spelling word once.</p>`;$('#answerArea').innerHTML=spellForm();$('.speak-btn').onclick=()=>speak(word,sentence);setTimeout(()=>speak(word,sentence),250)}
  else if(q.mode===1){const hidden=hideLetters(word);$('#modeBadge').textContent='🧩 Missing Letters';$('#promptArea').innerHTML=`<h2>Complete the word</h2><p class="instruction">Say it slowly and fill in the missing letters.</p><div class="letters">${[...hidden].map(c=>`<span class="letter ${c==='_'?'blank':''}">${c}</span>`).join('')}</div><button class="quiet hear-small">🔊 Hear the word</button>`;$('#answerArea').innerHTML=spellForm();$('.hear-small').onclick=()=>speak(word,sentence)}
  else{$('#modeBadge').textContent='⚡ Word Smash';$('#promptArea').innerHTML=`<h2>Spot the correct spelling</h2><p class="instruction">Which word is spelled correctly?</p><button class="quiet hear-small">🔊 Hear the word</button>`;$('#answerArea').innerHTML=`<div class="choices">${makeChoices(word).map(x=>`<button class="choice" data-answer="${x}">${x}</button>`).join('')}</div>`;$('.hear-small').onclick=()=>speak(word,sentence);$$('.choice').forEach(b=>b.onclick=()=>submit(b.dataset.answer))}
  const form=$('.spell-form');if(form){form.onsubmit=e=>{e.preventDefault();submit($('.spell-input').value)};setTimeout(()=>$('.spell-input').focus(),50)}
}
function spellForm(){return '<form class="spell-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the spelling"><button class="primary">Check</button></form>'}
function hideLetters(w){let chars=[...w];let positions=chars.map((_,i)=>i).filter(i=>i>0&&i<chars.length-1);positions.sort(()=>Math.random()-.5).slice(0,Math.max(2,Math.floor(w.length*.35))).forEach(i=>chars[i]='_');return chars.join('')}
function makeChoices(w){const variants=new Set([w]);const transforms=[x=>x.replace(/([aeiou])/,''),x=>x.slice(0,-1)+x.at(-1)+x.at(-1),x=>x.replace(/ie/,'ei'),x=>x.replace(/ou/,'u'),x=>x.replace(/([bcdfgmnprst])\1/, '$1'),x=>x.slice(0,2)+x[2]+x.slice(2)];for(const f of transforms){if(variants.size<4){const v=f(w);if(v!==w)variants.add(v)}}while(variants.size<4)variants.add(w+'e'.repeat(variants.size));return [...variants].sort(()=>Math.random()-.5)}
function normalise(x){return x.trim().toLowerCase().replace(/[^a-z'-]/g,'')}
function soundChunks(word){const patterns=['ough','aigh','eigh','tion','sion','ture','dge','igh','air','ear','ure','ph','wh','ch','sh','th','ng','qu','ck','ee','ea','ai','ay','oa','ow','oo','ou','oi','oy','er','ir','ur','ar','or','au','aw','ue','ew','ie'];const chunks=[];for(let i=0;i<word.length;){if(word[i]==="'"){i++;continue}const hit=patterns.find(p=>word.startsWith(p,i));chunks.push(hit||word[i]);i+=(hit||word[i]).length}return chunks}
function usefulParts(word){const prefixes=['inter','under','super','sub','dis','mis','in','re'],suffixes=['ation','tion','sion','ment','ness','less','ful','ally','ly','ing','ed','er'];const prefix=prefixes.find(x=>word.startsWith(x)&&word.length>x.length+2),suffix=suffixes.find(x=>word.endsWith(x)&&word.length>x.length+2);if(prefix&&suffix&&prefix.length+suffix.length<word.length)return[prefix,word.slice(prefix.length,-suffix.length),suffix];if(prefix)return[prefix,word.slice(prefix.length)];if(suffix)return[word.slice(0,-suffix.length),suffix];return soundChunks(word)}
function submit(answer){if(state.locked)return;state.locked=true;const q=current(),rec=state.records[q.data.word];rec.attempts++;const right=normalise(answer)===q.data.word;if(rec.firstCorrect===null)rec.firstCorrect=right;if(right){rec.correct=true;state.coins+=5;state.xp+=10;setFeedback(['Brilliant spelling!','Word magic!','You found it!'][Math.floor(Math.random()*3)],true);$('#owlFace').textContent='🦉✨';setTimeout(()=>{state.index++;renderQuestion()},900)}else{rec.correct=false;if(!q.repeat&&!q.scheduled){q.scheduled=true;state.queue.splice(Math.min(state.queue.length,state.index+3),0,{data:q.data,mode:(q.mode+1)%3,repeat:true})}showCorrection(q)}}
function showCorrection(q){const word=q.data.word;$('#feedback').innerHTML=`<div class="correction"><span>Good try! The correct spelling is</span><strong>${highlightTricky(word)}</strong><small>Listen to the help, then type it once more.</small></div><p class="support-heading">Your first help is open below. Try another strategy if you need it.</p><div class="support-buttons"><button class="support-btn" data-help="sounds">👆 Sound steps</button><button class="support-btn" data-help="syllables">👏 Syllables</button><button class="support-btn" data-help="parts">🧩 Word parts</button><button class="support-btn" data-help="tip">💡 Memory clue</button></div><div id="supportPanel" class="support-panel"></div>`;$('#feedback').className='feedback try';$('#answerArea').innerHTML=`<form class="spell-form correction-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the correct spelling again"><button class="primary">Try again</button></form><button class="secondary next-word">Next word →</button>`;$('#owlText').textContent='Take your time. Listen, look at the chunks, then type the word again.';$$('.support-btn').forEach(b=>b.onclick=()=>showSupport(word,b.dataset.help));showSupport(word,'sounds');$('.correction-form').onsubmit=e=>{e.preventDefault();const input=$('.correction-form .spell-input');if(normalise(input.value)===word){state.records[word].correct=true;state.coins+=3;state.xp+=5;$('#feedback').textContent='✓ That’s it! You helped your memory grow.';$('#feedback').className='feedback good';$('#owlFace').textContent='🦉✨';setTimeout(()=>{state.index++;renderQuestion()},1100)}else{input.value='';input.focus();$('#owlText').textContent=`Look carefully: ${word}. Copy each letter when you’re ready.`}};$('.next-word').onclick=()=>{state.index++;renderQuestion()};setTimeout(()=>{$('.correction-form .spell-input')?.focus();state.locked=false},100)}
function highlightTricky(word){const tricky=WORD_HELP[word]?.tricky;if(!tricky||!word.includes(tricky))return word;return word.replace(tricky,`<span class="tricky-part">${tricky}</span>`)}
function showSupport(word,type){const help=WORD_HELP[word]||{sounds:soundChunks(word),syllables:usefulParts(word),parts:usefulParts(word),tip:'Say it, notice the unusual spelling chunk, cover it, write it, then check.'},panel=$('#supportPanel');panel.hidden=false;if(type==='sounds'){panel.innerHTML=`<b>Listen and follow the sound chunks</b><p>Say the word slowly. Touch one box for each useful spelling chunk.</p><div class="sound-chips">${help.sounds.map(x=>`<i>${x}</i>`).join('')}</div>${help.build?`<p><b>Build the tricky beginning one letter at a time:</b></p><div class="build-steps">${help.build.map((x,i)=>`<span><small>${i+1}</small>${x}</span>`).join('<b>→</b>')}</div><p class="letter-order">Letter order: ${help.build.at(-1).toUpperCase().split('').join(' – ')}</p>`:''}`;speak(help.teaching||`${word}. ${help.sounds.join('. ')}`)}else if(type==='syllables'){panel.innerHTML=`<b>Clap and chunk the word</b><p>${help.syllables.join(' · ')}</p><div class="sound-chips">${help.syllables.map(x=>`<i>${x}</i>`).join('')}</div>`}else if(type==='parts'){panel.innerHTML=`<b>Build from useful word parts</b><p>Spot a prefix, root or suffix, then join the parts in order.</p><div class="sound-chips">${help.parts.map(x=>`<i>${x}</i>`).join('')}</div>`}else panel.innerHTML=`<b>Memory clue</b><p>${help.tip}</p>`}
function setFeedback(text,good){const el=$('#feedback');el.textContent=(good?'✓ ':'🌱 ')+text;el.className='feedback '+(good?'good':'try')}
function startBoss(){const records=Object.entries(state.records);const needs=records.filter(([,r])=>!r.firstCorrect).map(([w])=>w);const all=records.map(([w])=>w);state.boss=[...needs,...all.filter(w=>!needs.includes(w))].slice(0,Math.min(5,all.length));state.bossIndex=0;$('#bossIntro').textContent=state.questType==='weekly'?'Finish with the school words that need the most attention.':QUESTS[state.questNumber-1].test?'Path Test finale: recall five words without clues.':'Spell five words to help Glowtail light the whole forest!';show('boss');renderBoss()}
function renderBoss(){if(state.bossIndex>=state.boss.length){finish();return}const word=state.boss[state.bossIndex],data=state.activeWords.find(x=>x.word===word)||{word,sentence:`Spell ${word}.`};$('#bossProgress').textContent=`${state.bossIndex+1} / ${state.boss.length}`;$('#bossFeedback').textContent='';$('#bossChallenge').innerHTML=`<h3>Listen, then spell the word</h3><button class="speak-btn" aria-label="Hear the word">🔊</button><form class="spell-form"><input class="spell-input" autocomplete="off" autocapitalize="none" spellcheck="false" aria-label="Type the spelling"><button class="primary">Cast spell!</button></form>`;$('#bossChallenge .speak-btn').onclick=()=>speak(word,data.sentence);$('#bossChallenge form').onsubmit=e=>{e.preventDefault();submitBoss($('.boss-card .spell-input').value)};setTimeout(()=>speak(word,data.sentence),200)}
function submitBoss(answer){const word=state.boss[state.bossIndex];if(normalise(answer)===word){state.bossCorrect++;state.coins+=10;state.xp+=15;$('#bossFeedback').textContent='✨ The forest glows brighter!';$('#bossFeedback').className='feedback good'}else{$('#bossFeedback').textContent=`🌱 Nearly! It’s “${word}”. Every try builds memory.`;$('#bossFeedback').className='feedback try';speak(word)}setTimeout(()=>{state.bossIndex++;renderBoss()},1300)}
function finish(){const total=Object.keys(state.records).length,first=Object.values(state.records).filter(r=>r.firstCorrect).length,ratio=first/total,stars=ratio>=.8?3:ratio>=.5?2:1,secure=ratio>=.8||(ratio>=.7&&state.bossCorrect>=Math.ceil(state.boss.length*.8)),quest=QUESTS[state.questNumber-1];const result={date:new Date().toISOString(),type:state.questType,questNumber:state.questNumber,questTitle:quest?.title,records:state.records,attempts:Object.values(state.records).reduce((n,r)=>n+r.attempts,0)+state.boss.length,firstCorrect:first,coins:state.coins,stars,xp:state.xp,bossCorrect:state.bossCorrect,secure};saved.latest=result;if(state.questType==='weekly')saved.weeklyLatest=result;else if(state.questType==='focus')saved.focusLatest=result;else{saved.mainLatest=result;saved.questResults=saved.questResults||{};saved.questResults[state.questNumber]=result}saved.totalCoins=(saved.totalCoins||0)+state.coins;saved.totalStars=(saved.totalStars||0)+stars;if(secure&&state.questType==='main')saved.completedQuests=[...new Set([...(saved.completedQuests||[]),state.questNumber])];persist();$('#coinCount').textContent=saved.totalCoins;$('#starCount').textContent=saved.totalStars;$('#resultStars').textContent='⭐'.repeat(stars);$('#resultCoins').textContent='+'+state.coins;$('#resultWords').textContent=`${first}/${total}`;const weekly=state.questType!=='main',test=quest?.test,champion=secure&&state.questNumber===30;$('#resultEyebrow').textContent=weekly?'SIDEQUEST COMPLETE':test?'PATH TEST COMPLETE':`QUEST ${state.questNumber} COMPLETE`;$('#resultTitle').textContent=weekly?'Weekly words rescued!':champion?'Wordwood Champion!':test?'Path checkpoint reached!':'You lit up the Wordwood!';$('#resultUnlock').innerHTML=weekly?'<span>🏅</span><div><small>BONUS REWARD</small><b>School Word Hero badge earned!</b></div>':test?'<span>🏆</span><div><small>WORLD BADGE</small><b>Path Test badge earned!</b></div>':'<span>🎒</span><div><small>QUEST REWARD</small><b>New trail supplies unlocked!</b></div>';$('#resultMessage').textContent=weekly?(secure?'Brilliant work — this week’s words are looking secure!':'Great practice. The difficult words will be ready for another sidequest.'):(champion?'All 30 quests are secure. Your spelling adventure can continue through sidequests and replay.':secure?`Quest ${state.questNumber} is secure! Quest ${state.questNumber+1} is now ready.`:`Brilliant learning. Replay this quest to secure the tricky words and unlock the next step.`);$('#playAgain').textContent=weekly?'Play sidequest again':secure&&state.questNumber<30?`Continue to Quest ${state.questNumber+1}`:'Replay this quest';$('#playAgain').onclick=()=>weekly?start(state.questType):start('main',secure&&state.questNumber<30?state.questNumber+1:state.questNumber);show('results')}
function renderParent(){const r=saved.latest;renderProfiles();populateVoices();$('#emptyResults').hidden=!!r;$('#dashboard').hidden=!r;renderWeeklyEditor();if(!r)return;const entries=Object.entries(r.records);$('.parent-head p').textContent=`Latest results: ${r.type==='weekly'?'Weekly Word Sidequest':`Quest ${r.questNumber||1} · ${r.questTitle||''}`}.`;$('#pAttempts').textContent=r.attempts;$('#pAccuracy').textContent=Math.round(r.firstCorrect/entries.length*100)+'%';$('#pMastered').textContent=`${entries.filter(([,x])=>x.correct).length} / ${entries.length}`;$('#pStars').textContent=r.stars;$('#wordResults').innerHTML=entries.map(([w,x])=>`<span class="word-chip ${x.firstCorrect?'good':'practise'}">${x.firstCorrect?'✓':'↻'} ${w}</span>`).join('');const pats={};entries.filter(([,x])=>!x.firstCorrect).forEach(([w])=>{const d=(r.type==='weekly'?wordData(weeklyWords()):questWordData(QUESTS[(r.questNumber||1)-1])).find(x=>x.word===w);const p=d?.pattern||guessPattern(w);pats[p]=(pats[p]||0)+1});$('#patterns').innerHTML=Object.keys(pats).length?Object.entries(pats).sort((a,b)=>b[1]-a[1]).map(([p,n])=>`<div class="pattern"><span>${p}</span><b>${n} word${n>1?'s':''}</b></div>`).join(''):'<p>✨ No tricky patterns this time — lovely work!</p>'}
function activeProfile(){return profileBook.profiles.find(p=>p.id===profileBook.active)||profileBook.profiles[0]}
function persist(){
  if(saved.latest?.date&&saved.lastHistoryResultDate!==saved.latest.date){updateWordHistory(saved.latest);saved.lastHistoryResultDate=saved.latest.date}
  localStorage.setItem(`spellQuest:${profileBook.active}`,JSON.stringify(saved));localStorage.setItem('spellQuestProfiles',JSON.stringify(profileBook))
  renderConfidence()
}
function renderProfiles(){$('#profileSelect').innerHTML=profileBook.profiles.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');$('#profileSelect').value=profileBook.active}
$('#profileSelect').onchange=e=>{persist();profileBook.active=e.target.value;localStorage.setItem('spellQuestProfiles',JSON.stringify(profileBook));location.reload()};
$('#addProfile').onclick=()=>{const name=$('#newProfileName').value.trim();if(!name){$('#profileStatus').textContent='Enter a first name or nickname.';return}const id=`child-${Date.now()}`;profileBook.profiles.push({id,name:name.slice(0,40)});profileBook.active=id;localStorage.setItem('spellQuestProfiles',JSON.stringify(profileBook));localStorage.setItem(`spellQuest:${id}`,'{}');location.reload()};
function populateVoices(){const select=$('#voiceSelect');if(!select)return;const voices=availableVoices(),current=saved.voiceName||'';select.innerHTML='<option value="">Best available voice</option>'+voices.map(v=>`<option value="${v.name.replace(/"/g,'&quot;')}">${v.name} · ${v.lang}</option>`).join('');select.value=voices.some(v=>v.name===current)?current:'';const chosen=bestVoice(),british=chosen&&/^en-GB/i.test(chosen.lang);$('#voiceStatus').textContent=chosen?`Currently using ${chosen.name} (${chosen.lang})${british?'.':' — this device has no British voice installed.'}`:'Waiting for this device’s voice list…'}
if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=()=>populateVoices();
$('#voiceSelect').onchange=e=>{saved.voiceName=e.target.value;persist();populateVoices();speak('', 'Welcome to Spell Quest. Let’s discover some brilliant words together!')};
$('#previewVoice').onclick=()=>speak('', 'Welcome to Spell Quest. Let’s discover some brilliant words together!');
function renderWeeklyEditor(){const words=weeklyWords(),ready=words.length>=3;$('#customWords').value=words.join(', ');$('#weeklyReadyBadge').textContent=ready?`✨ Sidequest ready · ${words.length} words`:'Add at least 3 words';$('#weeklyReadyBadge').classList.toggle('ready',ready);$('#weeklyPreview').innerHTML=words.length?`<small>CURRENT LIST</small><div>${words.map(w=>`<span>${w}</span>`).join('')}</div>`:'<p>Your saved words will appear here.</p>';$('#parentSidequestStart').hidden=!ready;renderWeeklyEntrances()}
function parsedWords(text){return [...new Set(text.toLowerCase().split(/[\n,;]+/).map(normalise).filter(w=>w.length>1))].slice(0,1000)}
$('#saveWords').onclick=()=>{const words=parsedWords($('#customWords').value);if(words.length<3){$('#saveStatus').textContent='Please add at least 3 words.';return}saved.weeklyWords=words.slice(0,20);persist();renderWeeklyEditor();$('#saveStatus').textContent=`✓ ${saved.weeklyWords.length} words saved. The Weekly Word Sidequest is ready.`};
$('#clearWords').onclick=()=>{saved.weeklyWords=[];persist();renderWeeklyEditor();$('#saveStatus').textContent='Weekly list cleared. The main quests are unchanged.'};
async function importSheet(file){try{if(!window.XLSX)throw new Error('Spreadsheet reader unavailable. Check your internet connection.');const data=await file.arrayBuffer(),book=XLSX.read(data),sheet=book.Sheets[book.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''});if(!rows.length)throw new Error('The spreadsheet is empty.');const header=rows[0].map(x=>String(x).trim().toLowerCase()),wi=header.findIndex(x=>/word|spelling|keyword/.test(x)),start=wi>=0?1:0,wordCol=wi>=0?wi:0,imported=[];for(const row of rows.slice(start)){const word=normalise(String(row[wordCol]||''));if(word.length>1)imported.push(word)}saved.weeklyWords=[...new Set(imported)].slice(0,20);if(saved.weeklyWords.length<3)throw new Error('Please include at least 3 words in the first word or keyword column.');persist();renderWeeklyEditor();$('#saveStatus').textContent=`✓ Imported ${saved.weeklyWords.length} words from ${file.name}. Sidequest ready.`}catch(err){$('#saveStatus').textContent=err.message}}
$('#fileInput').onchange=e=>e.target.files[0]&&importSheet(e.target.files[0]);const dz=$('#dropZone');['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{const f=e.dataTransfer.files[0];if(f)importSheet(f)});
function classifyWord(word){if(/ough|eigh|aigh|igh/.test(word))return{name:'Complex vowel spellings',help:'Compare words with the same letter team, say the sound, then mark the unusual grapheme.'};if(/tion|sion|ture|cial|tial/.test(word))return{name:'Tricky endings',help:'Hear the ending as one chunk and sort words by the letters used to spell it.'};if(/^(re|dis|mis|in|im|sub|inter|super|anti|auto)/.test(word)||/(ment|ness|ful|less|ly|ous|ation)$/.test(word))return{name:'Prefixes, roots and suffixes',help:'Build the word from meaningful parts, keeping the root word visible.'};if(/([bcdfgmnprst])\1/.test(word))return{name:'Double consonants',help:'Say the syllables, find the stressed vowel and compare the root before adding an ending.'};if(/kn|wr|mb$|lk$|gn/.test(word))return{name:'Silent letters',help:'Highlight the silent letter and link the word to a memorable visual or word relative.'};if(['there','their','theyre','hear','here','two','too','to','where','were','wear','which','witch'].includes(word.replace(/'/g,'')))return{name:'Homophones and meaning',help:'Choose the spelling from a sentence and connect each form to its meaning.'};if(soundChunks(word).some(x=>x.length>1))return{name:'Sounds represented by letter teams',help:'Say the word clearly, segment it into phonemes, then choose a grapheme for each sound.'};return{name:'Unusual or whole-word spelling',help:'Use look–say–cover–write–check and retrieve the word again after a delay.'}}
function confidenceFor(stat){const rate=stat.seen?stat.firstCorrect/stat.seen:0;if(stat.seen>=2&&rate>=.8&&stat.recent?.slice(-2).every(Boolean))return{level:'secure',label:'Secure',score:3};if(rate>=.5||stat.recent?.at(-1))return{level:'growing',label:'Growing',score:2};return{level:'focus',label:'Needs practice',score:1}}
function updateWordHistory(result){saved.wordHistory=saved.wordHistory||{};Object.entries(result.records||{}).forEach(([word,record])=>{const stat=saved.wordHistory[word]||{seen:0,firstCorrect:0,totalAttempts:0,recent:[]};stat.seen++;stat.firstCorrect+=record.firstCorrect?1:0;stat.totalAttempts+=record.attempts||1;stat.recent=[...(stat.recent||[]),!!record.firstCorrect].slice(-5);stat.lastSeen=result.date;stat.pattern=classifyWord(word).name;saved.wordHistory[word]=stat})}
function renderConfidence(){const host=$('#confidenceWords');if(!host)return;const rows=Object.entries(saved.wordHistory||{}).map(([word,stat])=>({word,stat,confidence:confidenceFor(stat),type:classifyWord(word)})).sort((a,b)=>a.confidence.score-b.confidence.score||b.stat.seen-a.stat.seen||a.word.localeCompare(b.word));const focus=rows.filter(x=>x.confidence.level==='focus').slice(0,10),growing=rows.filter(x=>x.confidence.level==='growing').length,secure=rows.filter(x=>x.confidence.level==='secure').length;saved.focusWords=focus.map(x=>x.word);$('#confidenceSummary').innerHTML=rows.length?`<span class="confidence-count focus"><b>${focus.length}</b> needs practice</span><span class="confidence-count growing"><b>${growing}</b> growing</span><span class="confidence-count secure"><b>${secure}</b> secure</span>`:'<p>Complete a quest to begin tracking confidence.</p>';host.innerHTML=rows.map(({word,stat,confidence,type})=>`<div class="confidence-row"><div><b>${word}</b><small>${type.name} · seen ${stat.seen} time${stat.seen===1?'':'s'} · ${stat.firstCorrect}/${stat.seen} first try</small></div><div class="confidence-meter"><i class="${confidence.level}" style="width:${confidence.score/3*100}%"></i></div><span class="confidence-label ${confidence.level}">${confidence.label}</span></div>`).join('');const types={};focus.forEach(x=>{types[x.type.name]=types[x.type.name]||{...x.type,count:0,words:[]};types[x.type.name].count++;types[x.type.name].words.push(x.word)});$('#confidenceTypes').innerHTML=Object.values(types).sort((a,b)=>b.count-a.count).map(x=>`<div class="type-insight"><b>${x.name}</b><span>${x.words.join(', ')}</span><p>${x.help}</p></div>`).join('')||'<p>No repeated difficulty type is showing yet.</p>';$('#startFocusQuest').hidden=focus.length<3;$('#focusQuestNote').textContent=focus.length>=3?`Practice sidequest ready with: ${focus.map(x=>x.word).join(', ')}.`:rows.length?'A practice sidequest appears when at least 3 words need extra help.':'Confidence is stored separately for each child on this device.'}
renderConfidence();
